# Generated by Django 2.0.1 on 2018-01-30 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Definer')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subName', models.CharField(max_length=150)),
                ('extraName', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='unit',
            name='UnitType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.UnitType'),
        ),
        migrations.AddField(
            model_name='unit',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.District'),
        ),
        migrations.AddField(
            model_name='unit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Owner'),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Metric'),
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Program'),
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Unit'),
        ),
        migrations.AddField(
            model_name='job',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.JobType'),
        ),
        migrations.AddField(
            model_name='job',
            name='jobgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.JobGroup'),
        ),
        migrations.AddField(
            model_name='event',
            name='jobgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.JobGroup'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smthng.Region'),
        ),
    ]
